### ISSUE TITLE
numbered registers auto-increment don't work as described

### ISSUE THREAD

**Issue by Deracination** [iggredible/Learn-Vim#10]
In 'ch8_registers.md' the numbered registers don't autoincrement with '.'

'1p' followed by '.' will insert two copies of register 1.

**Comment by iggredible** [comment]
It works for me. If I understood it correctly, you were running `1p.` (typing "1", then typing "p", then typing "."). If that's what you were running, you were missing the `"` (double-quote) in `"1p`. Instead try doing `"1p.` (a double-quote, the number one, the letter p, then dot).

`1p` means put/paste once. `"1p` means put/paste from numbered register one.

I tested in while running Vim without any config (`vim -u NONE -U NONE -N -i NONE`).

![vim1p](https://user-images.githubusercontent.com/13905902/91439251-457c3c00-e832-11ea-8e2e-6f72d8fb1e04.gif)

**Comment by iggredible** [comment]
I close this, but if this is still an issue, please feel free to reopen another issue. Also try running it with Vim without any settings/plugins (your config could interfere).

**Comment by Deracination** [comment]
Sorry, I missed the double-quote " preceding the command!
