### ISSUE TITLE
Syntax in example ch13

### ISSUE THREAD

**Issue by victorhck** [iggredible/Learn-Vim#102]
Hello.

In ch13 in [this section](https://github.com/iggredible/Learn-Vim/blob/master/ch13_the_global_command.md#global-command-overview) the syntax of example is:
`:g/pattern/command`

and later in the same chapter in [other section](https://github.com/iggredible/Learn-Vim/blob/master/ch13_the_global_command.md#inverse-match) the syntax add a curly brackets:

`:g!/{pattern}/{command}`

it's right, or should use the same syntax?

Greetings

**Comment by iggredible** [comment]
Good point. To keep things simple, I'll remove the curly braces `{pattern}` and replace them with just `pattern`.
