### ISSUE TITLE
!}column -t -s "|" not work

### ISSUE THREAD

**Issue by rannuo** [iggredible/Learn-Vim#111]
`!}column -t -s "|"`

```sh
/bin/bash: }column: command not found

shell returned 127
```

**Comment by iggredible** [comment]
Hi @rannuo - It looks like your shell doesn't have the `column` command (to check if you have the `column` command, run `command -v column`).

`!` is a command that executes a shell command from inside Vim. If your shell doesn't have that command, it will fail to execute. Hope it makes sense!

https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script

**Comment by CyrusYip** [comment]
@iggredible I use zsh and got this problem, too. Here is the output: 

```
zsh:1: command not found: }column

shell returned 127

Press ENTER or type command to continue
```

But I have the `column` command. I can use it in zsh.

```
❯ command -v column
/usr/bin/column
❯ column -t -s "|" test
Id  Name    Cuteness
01  Puppy   Very
02  Kitten  Ok
03  Bunny   Ok
```

How can I fix this problem?
