### ISSUE TITLE
Meaning MVP in Chap 29

### ISSUE THREAD

**Issue by victorhck** [iggredible/Learn-Vim#146]
Hello!

I was translating Chap29 and I found:

>  For MVP, this command was good enough, 

What does mean MVP in this context? (Maybe a silly question...)

Greetings

**Comment by kotp** [comment]
I would translate that to be "minimum viable product".  It basically indicates the smallest demonstrable working product.

**Comment by iggredible** [comment]
Hey! Sorry for super late reply, work has been super busy I haven't had much time with anything else :D. Yup! MVP here means Minimum Viable Product, and yes, it is the smallest demonstrable working product. Basically what's the least I can have before I can consider it complete / "good enough"?

**Comment by kotp** [comment]
It would be good to define any abbreviations on first use, and if some time (chapters) have passed, perhaps an indication where it is defined.  Abbreviations are troublesome when this does not happen, especially for those reading in a language that may not be their native language or native industry.

**Comment by iggredible** [comment]
Good point! Looking back, it is a business jargon. I revised the sentence to replace it with something that I think is more understandable :)

**Comment by victorhck** [comment]
I think that is better...
Thanks a lot for your work!!  :)

**Comment by iggredible** [comment]
Yeah, np! Appreciate your inputs :)
