### ISSUE TITLE
Include \zs,\ze in search and substitue lesson

### ISSUE THREAD

**Issue by ThangaAyyanar** [iggredible/Learn-Vim#19]
As a quick example, say you have a line like
```
test testing tester
```
:s/test/foo/g gives **foo fooing fooer**     
:s/\zstest\zeing/foo gives **test fooing tester**

reference: https://www.reddit.com/r/vim/comments/ijy2gb/flygrep_grep_and_replace_on_the_fly_in_a_project/

**Comment by iggredible** [comment]
Good suggestion! I am out of town with family, but I will update it as soon as I can!

**Comment by iggredible** [comment]
Updated [Ch 12](https://github.com/iggredible/Learn-Vim/blob/master/ch12_search_and_substitute.md) to include `\ze`, `\zs`, and even more regex goodness. Closing this issue.
