### ISSUE TITLE
can i transfer it to my native language

### ISSUE THREAD

**Issue by godcong** [iggredible/Learn-Vim#21]
Hi dear,
    I want transfer it to my native language.
    But your licensed looks i cannot make any changes, including translation.
    So i'm not sure if i can translate it

In addition, maybe you can add language management. 
I think many people are willing to add the translation pr in your book(including me).

**Comment by iggredible** [comment]
Great suggestion. 

This project was under the CC NonCommercial NonDeriv and I just realized the "NonDeriv" part didn't allow derivatives (which in this case includes translation). 

I changed the license into [CC NonCommercial ShareAlike](https://creativecommons.org/licenses/by-nc-sa/4.0/). You can now remix, transform, and build upon the material - including translating.

As for language management, I think I am going to create a branch named after the appropriate ISO language.

So this part is up to you:

1. If you rather create a mirror repo, feel free to do that (just make sure to give proper credit and keep the same license. 
2. If you rather submit a PR to this project, I can create a new branch that you can PR to.

**Comment by wsdjeg** [comment]
@godcong hi，seems you are chinese too. Can we do it together? please checkout #22

**Comment by godcong** [comment]
I prefer to PR to this project because it will be more convenient for those who need it to find their own native language version.
@wsdjeg What do you think?

**Comment by wsdjeg** [comment]
no, translate link cound be added to readme of this project. same as vim-galore.

**why?**

1. the general discussion of translation will be in chinese. people who watching this repo maybe do not want to get notification in chinese.

2. after translationg done. the general usage discussion or other thing relative to the chinese version can be discussed in separate issue stack in chinese.

**Comment by godcong** [comment]
Both are ok.

**Comment by victorhck** [comment]
I was thinking about translate to spanish too (and maybe use gitbook or similar to publish). So, the proper way should be clone this one in a local repo in my account and start translation?

**Comment by godcong** [comment]
We are discussing two options.
1.  Create a branch named after the appropriate ISO language.

2.  Fork/Clone this project yourself, and then these projects point to each other. I think gitbook should be the same.

But I am not sure which way the author prefers

**Comment by iggredible** [comment]
Good pros and cons. I agree with @wsdjeg reasoning that it is better to start it on a separate Repo. If there are 10 different language translations, we may (potentially) have 10x more PRs in different languages - and as a repo owner who mainly speaks English, I wouldn't know how to handle them. 

Let's say @godcong or @wsdjeg create a fork for a Chinese translation together and receives a PR in Chinese, they will know how to handle it in their own language. The same if someone submits a Spanish PR, @victorhck will be able to handle it.

I think it's better if you all create a separate fork for each language.

In addition, when the translation works are done, feel free to let me know and I will include a link to each translation repo in the main README so people know they exist.

**Comment by wsdjeg** [comment]
@iggredible Ok, I have created the [chinese version repo](https://github.com/wsdjeg/Learn-Vim_zh_cn), and the translation is WIP now. @godcong feel free to send PR if you want to translate it together, now we have pick up ch 0-8.

**Comment by iggredible** [comment]
Excellent. I have updated the README to include the translation link.
I will close this issue. Feel free to reopen a new one as needed. 

Thanks!
