### ISSUE TITLE
Chinese version of Learn-Vim

### ISSUE THREAD

**Issue by wsdjeg** [iggredible/Learn-Vim#22]
hello @iggredible, Thank for sharing. I am maintainer of @vim-china. And can we translate this into chinese? Just same as [vim-golare_zh_cn](https://github.com/wsdjeg/vim-galore-zh_cn) did by us.

https://github.com/wsdjeg/Learn-Vim_zh_cn/issues/1

**Comment by iggredible** [comment]
Definitely!

Btw, I recently relicensed this project from [CC-NC-ND](https://creativecommons.org/licenses/by-nc-nd/4.0/) to [CC-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/) so you can now create a translation for this project. 

I see that you also saw another request (#21 ) to translate it to CH. Feel free to work it out together. I will keep this as an open issue for now.

**Comment by wsdjeg** [comment]
Thanks the translation is WIP now.

**Comment by iggredible** [comment]
Sounds good. I will close this issue. Feel free to open a new one if you have another question.
