### ISSUE TITLE
Proposal for a translation to Korean

### ISSUE THREAD

**Issue by Machineric** [iggredible/Learn-Vim#24]
First of all, thanks for this amazing project.
It seems like no one is working for a Korean version yet.
I'd like to work on it if you wouldn't mind!

**Comment by iggredible** [comment]
Definitely. Feel free to mirror the repo and work on it.

1. Let me know what the appropriate ISO language code is from [this list](http://www.lingoes.net/en/translator/langcode.htm) (I think it's either `ko` or `ko-KR`?)
2. When you've created the repo, send me the link in here and I'll add it to README.
3. Per license, keep the same license that I have (Creative-Commons NonCommercial ShareAlike).

That's it!
