### ISSUE TITLE
Spansish translation (WIP)

### ISSUE THREAD

**Issue by victorhck** [iggredible/Learn-Vim#25]
Working (or having fun) in the spanish translation for your text about learn Vim in a smart way:
https://github.com/victorhck/learn-Vim-es
Translate, improve, fix... PR are wellcome!!

Thanks for your work!!

**Comment by iggredible** [comment]
It looks pretty good. Thanks for working on the translation. 
If I have to put down the appropriate ISO language code from this list (http://www.lingoes.net/en/translator/langcode.htm), what would it be? 

`es`?
