### ISSUE TITLE
Mixed use of  the magic syntax ( \v ) and  escape special characters . 

### ISSUE THREAD

**Issue by JefferyJu** [iggredible/Learn-Vim#36]
hello, in `Capturing a Phone Number` of  `ch12_search_and_substitute.md` ,  mixed  of  the magic syntax ( `\v` ) and  escape special characters
```
/\d\{3\}-\d\{3\}-\d\{4\}
```
```
/\v\d{3}-\d{3}-\d{4}
```

**Comment by iggredible** [comment]
Good catch @JefferyJu !
Fixed it: https://github.com/iggredible/Learn-Vim/blob/master/ch12_search_and_substitute.md#capturing-a-phone-number
