### ISSUE TITLE
Vim Runtime

### ISSUE THREAD

**Issue by ThangaAyyanar** [iggredible/Learn-Vim#42]
Chapter about vim runtime would be great.

My Favorite resource:
- https://www.youtube.com/watch?v=JFr28K65-5E

**Comment by iggredible** [comment]
Interesting - I actually thought about it (and it was in an early draft of one of the chapters). 

I'll give it more thoughts.

**Comment by iggredible** [comment]
Finished watching the vid. This is a great suggestion. I will include it in the upcoming chapters.

I'll close this Issue. Feel free to open a new one. Stay tuned!
