### ISSUE TITLE
Vim Plugins

### ISSUE THREAD

**Issue by mo1ein** [iggredible/Learn-Vim#43]
I think chapter about vim plugins can very helpful. For example introduce some powerful vim plugins and teach how install and config them, because these tools makes vim a cool IDE :sunglasses:

Some useful plugins are : 
* https://github.com/ycm-core/YouCompleteMe
* https://github.com/deoplete-plugins/deoplete-jedi
* https://github.com/dense-analysis/ale
* https://github.com/preservim/nerdtree
* https://github.com/Yggdroot/indentLine
* https://github.com/ryanoasis/vim-devicons
* https://github.com/vim-airline/vim-airline
* https://github.com/tpope/vim-fugitive
* https://github.com/iamcco/markdown-preview.vim

**Comment by iggredible** [comment]
Oh, good idea! I was on the fence about writing chapter like this. I think I will add one (or two) chapters on vimrc and plugin. Stay tuned!

I will close this Issue - feel free to open another one as needed.
