### ISSUE TITLE
An explanation a bit confusing?

### ISSUE THREAD

**Issue by victorhck** [iggredible/Learn-Vim#58]
Working in my translation of your guide I found an explanation of one command a bit confusing. I refer to the part you brake it down this comand:

https://github.com/iggredible/Learn-Vim/blob/master/ch13_the_global_command.md#reduce-multiple-empty-lines-to-one-empty-line

Don't know if the text can be improved to gain clarity when reading the text...
If not, I should to think again how to translate the best way possible!! :)

Greetings!

**Comment by iggredible** [comment]
I'll reread it tomorrow when I am free. Thanks for bringing it up @victorhck

**Comment by iggredible** [comment]
@victorhck I've updated it. Let me know if it is clearer now. If it is still confusing, let me know what part it is that is still unclear. I will leave this issue open for 2 more days or until you say it is good :)

**Comment by victorhck** [comment]
looks better to me!
Thanks a lot!!!

**Comment by iggredible** [comment]
You're welcome. Thanks for bringing it up. It would have escaped my attention.
