### ISSUE TITLE
issues with Spanish Updated

### ISSUE THREAD

**Issue by victorhck** [iggredible/Learn-Vim#64]
Hello Igor.
I ask you to remove the link to Spanish Updated version. Since that repo is a copy of my translation, but without respect my work with translation and the license (CC-by-sa-nc).
That is not a fork of mine. He has copied the files and create his own repo. And I have spend many hours doing translation, reviews, etc that not appears in that repo.
Greetings

**Comment by iggredible** [comment]
Hey @victorhck - thanks for notifying me. I'm sorry that I didn't catch it when I approved the PR.
I am actually out of town this weekend, so I will check it out sometimes this weekend. I'll look it up as soon as I am able to!

**Comment by iggredible** [comment]
@EliazBobadilla I compared some of the chapters between @victorhck's work and yours and it looks like it is an exact replica of Victor's (which later you updated them). Here's me running a vimdiff between Victor's work and yours (Eliaz = left, Victor = right). They look 95% the same, word-per-word.

![vimdiff between victor and eliaz repo](https://user-images.githubusercontent.com/13905902/106365110-8cde8b00-62f0-11eb-9d71-633859a65c50.png)

Per this project's license, if you pick up a project using someone else's content, you need to give a proper attribution. [Source](https://creativecommons.org/faq/). I think this was unintentional on your part, Eliaz, and you didn't mean harm.

There is no need to have two nearly identical/ parallel translations, so I will remove yours from the README, Eliaz. If I understand you correctly, it sounds like your translation will be updated more often. In that case, if you want to continue working on the Spanish translation, I think the best way is to submit PRs to Victor's repository, the original Spanish fork.

I will close this issue.

**Comment by EliazBobadilla** [comment]
Hi! I'm actually giving it credits:
![image](https://user-images.githubusercontent.com/71897736/106370637-d6979780-6329-11eb-966b-c1133a755a20.png)
- Spanish:
Debo comentar que he sacado los textos del Capitulo 1 al 15 de este usuario. 
- English:
I must comment that I have taken the texts of Chapter 1 to 15 of this user.
Also:
![image](https://user-images.githubusercontent.com/71897736/106370657-22e2d780-632a-11eb-8804-c138caed70e2.png)
Basically there it says that if he wants me to make a change in his mention, he will tell me and I will.
https://github.com/EliazBobadilla/Tutorial-de-VIM-en-ES/issues/1
I would also like to remind you that the reason why I made that Fork is because his version is out of date.
In fact as of this writing it is still very outdated.He has only translated it up to chapter 17...Everything that follows after that is in English as such you can review for yourself.
![image](https://user-images.githubusercontent.com/71897736/106370741-0f843c00-632b-11eb-9641-9eb94061d4bd.png)
https://github.com/victorhck/learn-Vim-es/blob/master/ch17_fold.md
I would also like to say that I plan to rewrite almost everything that @victorhck  wrote since in some parts it is not understood...
After mentioning all this I would like my version to continue in the readme...

**Comment by iggredible** [comment]
I don't think it is necessary to have two different independent translations. I prefer to have just one translation for each language.

If the current Spanish translation is not recent, it is more efficient if you submit PRs for the chapters that aren't done and for the parts that aren't understood to the current translation project.

Thanks.

**Comment by victorhck** [comment]
Hello.
First, my work is not outdated, it's a work in progress, there's a huge difference! I'm still working in translation as you see [here](https://github.com/victorhck/learn-Vim-es/graphs/commit-activity)
I have spent many hours doing translations, review text, update text with changes upstream, and even fix typos upstream. And learning in the way new things about Vim.

You could fork the whole repo and then in your repo work in your translation and send PR or not, you are free to do what ever, but with credits and attributions to original author and original repo. Git keeps that history when you fork the repo. But you downloaded my translations and uploaded to your repo, it's quite different. And only added a small reference after opened an issue.

I have been doing translations in free software communities since many years, in openSUSE community, wiki. And for other packages like [this](https://github.com/patrovite/Course_Generator/graphs/contributors) or [this](https://github.com/crow-translate/hugo-website/graphs/contributors), among many other projects (like FSF supporter). I'm not a developer, so this is the way I contribute with free software.
So I have experience doing translations, but all can be improved of course! so you are free to do it. But I don't think that my translations are hard to understood.

Well, let's pick an example in your translation in chapter 19.
This is the original made by @iggredible 

![igor](https://user-images.githubusercontent.com/1514206/106393055-1a0b0800-63f5-11eb-9bd5-48c0c90f2b1e.png)

and this is yours:

![eliaz](https://user-images.githubusercontent.com/1514206/106393227-39566500-63f6-11eb-8e0a-faa5a74ee0ec.png)

* You didn't keep the markdown syntax, so the part that is code, here appears among double quotes ¿? it's a bit confusing, isn't it?
* Where is the "makefile" section?? Well, let's continue
* You even translated the **:make** command with **:hacer**  OMG! I can see the face of that user trying to execute **:hacer** inside Vim O_o
* or in the same weird translation you did it again with: **:make build** you even translated that with **: hacer construir** :facepalm: 
* also is usual to see the term **run** translated as **corre** instead as **ejecuta** that I this is more exact (The GNU Project also thinks the same as you can see [here](https://www.gnu.org/server/standards/translations/es/recursos.html#R) BTW add this page to your bookmarks)

and all in a few lines in a small section of your contribution. I will stop at this point... 

Greetings and happy hacking...

**Comment by EliazBobadilla** [comment]
About what you say about the little mention, I told you to tell me what changes I should make in this [Issue](https://github.com/EliazBobadilla/Tutorial-de-VIM-en-ES/issues/1). Which by the way you didn't even answer.

Well, I don't want to discuss any more so I'll just delete [my repository](https://github.com/EliazBobadilla/Tutorial-de-VIM-en-ES).
I'm 14 years old, I'm studying on my own, I love Vim and I just wanted to contribute when I saw the project.

Greetings and happy hacking ...

**Comment by victorhck** [comment]
>  I'm 14 years old, I'm studying on my own, I love Vim and I just wanted to contribute when I saw the project.

You can.

**Comment by iggredible** [comment]
I appreciate the intention and the effort you put into it. You're 14? That's really cool. You are many years ahead of me (I wish I had your enthusiasm when I was your age).

Please don't let this event discourage you. Keep it up!
