### ISSUE TITLE
Typo or not?

### ISSUE THREAD

**Issue by victorhck** [iggredible/Learn-Vim#66]
Hello!
In chapter 16 in [this section](https://github.com/iggredible/Learn-Vim/blob/master/ch16_tags.md#tags-navigation) I found the word **milage**
Don't know what does it mean. Not sure if its a typo or it's right.

Greetings.

**Comment by iggredible** [comment]
Hello @victorhck - it was actually a typo. I meant to write "mileage", but instead I typed "milage". 
I'll fix it, thanks and good catch!

**Comment by iggredible** [comment]
Ok, fixed it. The word mileage refers to car mileage. Having a good mileage means being able to go far and to do many things.

In this context, Ctrl-] lets you do many things already, but it won't hurt to learn more.
