### ISSUE TITLE
Suggestion in chapter 00

### ISSUE THREAD

**Issue by victorhck** [iggredible/Learn-Vim#70]
Hello.
In the [chapter 00](https://github.com/iggredible/Learn-Vim/blob/master/ch00_new_to_vim_read_this_first.md#how-to-read-this-guide) you can read:

> The :help command and Google are your best friends.

Well, many people out there (like me) have another *best friends* when we are talking about search engines. :)
Can that sentence change a bit to include not only just one brand?
Greetings

**Comment by iggredible** [comment]
Fair enough. I use DuckDuckGo sometimes too. 
I updated "Google" to "search engines".
