### ISSUE TITLE
Editando capitulo 21

### ISSUE THREAD

**Issue by gamba47** [iggredible/Learn-Vim#79]
Hola, gracias por tomarte el trabajo en la edicion del documento, si te parece bien voy a tratar esta semana de traducir y pasarte el ch21_vimrc.md

Ya lo empece, pero no se como voy a estar de tiempos (estoy recien llegado de vacaciones y seguro algo me pasa)

Saludos! y perdon si este no es el medio.

**Comment by iggredible** [comment]
Hello @gamba47 , if you find any issue on Ch21 (or have some suggestions), feel free to just submit a PR. I'll review it and we can discuss it. 

(I am using Google translate on your issue, so I apologize if I'm missing anything) :)

**Comment by gamba47** [comment]
Hi iggredible!! sorry this is for other user who is translating your document i put this issue in the wrong place 

Closing this comment!
