### ISSUE TITLE
missing word in ch20?

### ISSUE THREAD

**Issue by victorhck** [iggredible/Learn-Vim#80]
Hello.
in [chapter 20, Viminfo](https://github.com/iggredible/Learn-Vim/blob/master/ch20_views_sessions_viminfo.md#viminfo) section you can read:

> the next time you open Vim you still that text stored in the register.

Reading that I found a bit weird... maybe missing a word after "still"... or maybe I'm wrong...

Greetings!

**Comment by iggredible** [comment]
Good point! I read this so much that I didn't notice the error. It's missing the word "have". It would also help if I clarify what "the register" means.

"...the next time you open Vim you still that text stored in the register." -> should be "...the next time you open Vim you still have that text stored in register a".

I'll make the changes. Good eye!
